### ISSUE TITLE
Tp2

### ISSUE THREAD

**Issue by CrissRMFI** [CrissRMFI/TP2---BEFUNGE-93#2]

**Comment by lihuencarranza** [comment]
Buenas chicos, les quería consultar donde está el archivo project.clj que especifica donde está el main. Gracias!

**Comment by CrissRMFI** [comment]
Buen día. Es el archivo core.clj
El comando que creó el proyecto creo ese archiv, ahí está el -main. Luego en la carpeta core pusimos los otros archivos .clj

**Comment by lihuencarranza** [comment]
# Corrección TP

Buenas chicos, acá les dejo la corrección de su trabajo:

- Me gustó que hayan dividio las respondabilidades en diferentes namespaces porque separa la lógica y es claro de leer. Se llega a una buena modularidad para posibles extensiones en un futuro.
- Estan utilizando un loop explcítio en vez de funciones de alto nivel como iterate. A veces se repite la lógca (pila/obtener-elemento y pila/colocar-elemento). Entiendo que priorizaron la claridad antes que la redundancia.
- Me habría gustado que usen funciones estandar de Clojure en vez de implementaciones explícitas (map, update, assoc, mod, etc)

Todas las pruebas pasan exitosamente.

# Nota: 8

Si les interesa subir a un 9, pueden reentregar utilizando funciones de Clojure.

Saludos
